{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "mysql55-mysql",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Not affected",
      "package_name": "mysql",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Not affected",
      "package_name": "mariadb",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "mariadb:10.3/mariadb",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "mysql:8.0/mysql",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Not affected",
      "package_name": "mariadb-galera",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Not affected",
      "package_name": "mariadb",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Not affected",
      "package_name": "rh-mariadb103-mariadb",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Not affected",
      "package_name": "rh-mysql80-mysql",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-11-18T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-28912 mariadb: Named pipe permission issue on Windows",
    "id": "1899332",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1899332"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:L",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-282",
  "statement": "This issue did not affect any version of MariaDB or MySQL as included in Red Hat products, as it only affected the versions of MariaDB or MySQL running on the Microsoft Windows platform.",
  "acknowledgement": "",
  "name": "CVE-2020-28912",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": null
}