{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Out of support scope",
      "package_name": "python-flask-cors",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2020-08-31T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2020-25032 python-flask-cors: allows ../ directory traversal to access private resources",
    "id": "1876698",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1876698"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-22",
  "statement": "While Red Hat Quay 3.1 includes an affected Flask-CORS version it doesn't use resource matching to protect private resources. Therefore we rated this issue low impact for Red Hat Quay 3.1. Later versions of Red Hat Quay are unaffected because they don't include the affected Flask-CORS library.",
  "acknowledgement": "",
  "name": "CVE-2020-25032",
  "document_distribution": "",
  "details": [
    "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows ../ directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format."
  ],
  "references": null
}