{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:python-rsa_project:python-rsa:*:*:*:*:*:*:*:*",
            "versionStartIncluding": "2.1",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      },
      {
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:redhat:openstack_platform:13.0:*:*:*:*:*:*:*",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:redhat:openstack_platform:16.0:*:*:*:*:*:*:*",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-25658"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "It was found that python-rsa is vulnerable to Bleichenbacher timing attacks. An attacker can use this flaw via the RSA decryption API to decrypt parts of the cipher text encrypted with RSA."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-327"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658",
          "refsource": "CONFIRM",
          "tags": [
            "Issue Tracking",
            "Third Party Advisory"
          ],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25658"
        },
        {
          "name": "https://github.com/sybrenstuvel/python-rsa/issues/165",
          "refsource": "MISC",
          "tags": [
            "Exploit",
            "Issue Tracking",
            "Third Party Advisory"
          ],
          "url": "https://github.com/sybrenstuvel/python-rsa/issues/165"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV2": {
      "acInsufInfo": false,
      "cvssV2": {
        "accessComplexity": "LOW",
        "accessVector": "NETWORK",
        "authentication": "NONE",
        "availabilityImpact": "NONE",
        "baseScore": 5,
        "confidentialityImpact": "PARTIAL",
        "integrityImpact": "NONE",
        "vectorString": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
        "version": "2.0"
      },
      "exploitabilityScore": 10,
      "impactScore": 2.9,
      "obtainAllPrivilege": false,
      "obtainOtherPrivilege": false,
      "obtainUserPrivilege": false,
      "severity": "MEDIUM",
      "userInteractionRequired": false
    },
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 7.5,
        "baseSeverity": "HIGH",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 3.9,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2020-12-02T15:27Z",
  "publishedDate": "2020-11-12T14:15Z"
}