{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2020-4388"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM Cognos Analytics 11.0 and 11.1 could be vulnerable to a denial of service attack by failing to catch exceptions in a servlet also exposing debug information could also be used in future attacks. IBM X-Force ID: 179270."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "ibm-cognos-cve20204388-dos (179270)",
          "refsource": "XF",
          "tags": [],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/179270"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/6346922",
          "refsource": "CONFIRM",
          "tags": [],
          "url": "https://www.ibm.com/support/pages/node/6346922"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2020-10-12T14:15Z",
  "publishedDate": "2020-10-12T14:15Z"
}