{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2021-3177"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Python 3.x through 3.9.1 has a buffer overflow in PyCArg_repr in _ctypes/callproc.c, which may lead to remote code execution in certain Python applications that accept floating-point numbers as untrusted input, as demonstrated by a 1e300 argument to c_double.from_param. This occurs because sprintf is used unsafely."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugs.python.org/issue42938",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugs.python.org/issue42938"
        },
        {
          "name": "https://github.com/python/cpython/pull/24239",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/python/cpython/pull/24239"
        },
        {
          "name": "https://python-security.readthedocs.io/vuln/ctypes-buffer-overflow-pycarg_repr.html",
          "refsource": "MISC",
          "tags": [],
          "url": "https://python-security.readthedocs.io/vuln/ctypes-buffer-overflow-pycarg_repr.html"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2021-01-19T06:15Z",
  "publishedDate": "2021-01-19T06:15Z"
}