{
  "debianbug": 970099,
  "description": "In Lib/tarfile.py in Python through 3.8.3, an attacker is able to craft a TAR archive leading to an infinite loop when opened by tarfile.open, because _proc_pax lacks header validation.",
  "releases": {
    "stretch": {
      "nodsa": "Minor issue, can be fixed in next DLA",
      "nodsa_reason": "postponed",
      "repositories": {
        "stretch": "3.5.3-1+deb9u1",
        "stretch-security": "3.5.3-1+deb9u2"
      },
      "status": "open",
      "urgency": "low"
    }
  },
  "scope": "local"
}